{
	"version": 1722505076,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/coin-sheet0.png",
		"images/home-sheet0.png",
		"images/replay-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/chest-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/flag-sheet0.png",
		"images/flag-sheet1.png",
		"images/flag-sheet2.png",
		"images/sprite17-sheet0.png",
		"images/sprite19-sheet0.png",
		"media/get coin.m4a",
		"media/get coin.ogg",
		"media/start.m4a",
		"media/start.ogg",
		"media/win sound.m4a",
		"media/win sound.ogg",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/rain-in-forest-birds-nature-111405.m4a",
		"media/rain-in-forest-birds-nature-111405.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/walksound.m4a",
		"media/walksound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}